#!/bin/bash

if [[ ! -f /usr/libexec/PlistBuddy ]]; then
    exit 0
fi

PLIST=platforms/ios/*/*-Info.plist

# Bypass ATS for test servers
cat << EOF |
Delete :UIBackgroundModes
Add :UIBackgroundModes array
Add :UIBackgroundModes:0 string 'remote-notification'
EOF
while read line
do
    /usr/libexec/PlistBuddy -c "$line" $PLIST
done
